# Generated by Django 6.0.3 on 2026-05-03 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("agents", "0002_agentregistration_created_at_and_more"),
        ("properties", "0002_alter_propertyregistration_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="RecordPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("amount", models.DecimalField(decimal_places=0, max_digits=10)),
                ("transaction_id", models.CharField(max_length=50)),
                (
                    "agent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="agents.agentregistration",
                    ),
                ),
                (
                    "landlord",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="properties.propertyownership",
                    ),
                ),
            ],
        ),
    ]
