# Generated by Django 6.0.3 on 2026-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AgentRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("username", models.CharField(max_length=20)),
                ("phone", models.IntegerField()),
                ("address", models.CharField(max_length=100)),
                ("no_of_properties", models.IntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("warning", "Warning"),
                            ("suspended", "Suspended"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
