# Generated by Django 6.0.3 on 2026-04-05 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("properties", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="propertyregistration",
            name="status",
            field=models.CharField(
                choices=[
                    ("occupied", "Occupied"),
                    ("available", "Available"),
                    ("under_review", "Under Review"),
                ],
                default="under_review",
                max_length=50,
            ),
        ),
    ]
